services:
  salt_master:
    volumes:
      - ../e2e_test/:/test/:ro
      - ./states:/srv/salt/:ro
      - ./ipc.ignore:/var/run/salt/master/

  exporter:
    volumes:
      - ../:/app/:ro
      - ./ipc.ignore:/var/run/salt/master/:ro

  # recorder:
  #   image: ghcr.io/charmbracelet/vhs:v0.5.1-devel
  #   entrypoint: tail -f /dev/null
  #   working_dir: /app
  #   user: "${UID}:${GID}"
  #   volumes:
  #     - ../:/app/:rw
  #     - ipc:/var/run/salt/master/:ro
  #   depends_on:
  #     minion:
  #       condition: service_healthy
