before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/salt-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - replacements:
      linux: Linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: 'Breaking changes'
      regexp: '^.*?(\([[:word:]]+\))??!:.+$'
      order: 0
    - title: 'Enhancements'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Internal'
      regexp: '^.+$'
      order: 999
