before:
  hooks:
    - go mod tidy

builds:
  - id: salt-exporter
    binary: salt-exporter
    main: ./cmd/salt-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
  - id: salt-live
    binary: salt-live
    main: ./cmd/salt-live
    env:
      - CGO_ENABLED=0
    goos:
      - linux

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: 'Breaking changes'
      regexp: '^.*?(\([[:word:]]+\))??!:.+$'
      order: 0
    - title: 'Enhancements'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Internal'
      regexp: '^.+$'
      order: 999
