name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COMPOSE_FILE: e2e_test/docker-compose.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Build salt-exporter
      run: go build -v ./cmd/salt-exporter

    - name: Build salt-live
      run: go build -v ./cmd/salt-live

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.2.0

    - name: Test
      run: go test -v ./...

  e2e:
    name: "End to End tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Set up environment
        run: docker compose -f $COMPOSE_FILE up -d

      - name: Give some time to Salt
        run: sleep 30

      - name: Run some Salt commands
        run: docker compose -f $COMPOSE_FILE exec salt_master sh /test/exec_commands.sh

      - name: Test
        run: go test -v -tags=e2e ./e2e_test/...

      - name: "Clean up environment"
        if: always()
        run: docker compose -f $COMPOSE_FILE down
