name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Build salt-exporter
      run: go build -v ./cmd/salt-exporter

    - name: Build salt-live
      run: go build -v ./cmd/salt-live

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.2.0

    - name: Test
      run: go test -v ./...
